stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - cp /home/openroad/flow_runner.env src/.env
  script:
    - docker-compose build
  only:
    - master
  tags:
    - openroad
    - flow
    - runner

deploy:
  stage: deploy
  before_script:
    - cp /home/openroad/flow_runner.env src/.env
  script:
    - docker-compose up -d
  only:
    - master
  tags:
    - openroad
    - flow
    - runner