version: '3'

volumes:
  flow_runner_postgress_data: {}
  flow_runner_broker_data: {}

services:
  postgres:
    image: postgres:9.6
    container_name: flow_runner_db
    volumes:
      - flow_runner_postgress_data:/var/lib/postgresql/data
    env_file: src/.env

  broker:
    image: redis:5.0.4
    volumes:
      - flow_runner_broker_data:/data
    container_name: flow_runner_broker

  openroad:
    build:
      context: .
      dockerfile: ./deployment/web/Dockerfile
    container_name: flow_runner
    depends_on:
      - postgres
    env_file: src/.env
    ports:
      - "8000:8000"
    links:
      - postgres

  celery:
    build:
      context: .
      dockerfile: ./deployment/celery/Dockerfile
    container_name: flow_runner_celery
    depends_on:
      - postgres
      - broker
      - openroad
    env_file: src/.env
    links:
    - postgres